# Site settings
title: Archmix.org
email:
description: 

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://archmix.org" # the base hostname & protocol for your site

google_analytics: 
addthis_id: 
disqus_account: 

puzzly-devx-repo: https://github.com/archmix/puzzly-devx
puzzly-oss-repo: https://github.com/archmix/puzzly-oss

social:
  - title: twitter
    url: https://twitter.com/archmixorg
  - title: github
    url: http://github.com/archmix
  - title: slack
    url : https://archmix.org/slack

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

assets_location: //raw.githubusercontent.com/archmix/community/master/assets

collections:
  sections:
    output: false
