# Site settings
title: Archmix.org
email:
description: 

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://archmix.org" # the base hostname & protocol for your site

google_analytics: 
addthis_id: 
disqus_account: 

social:
  - title: twitter
    url: https://twitter.com/archmixorg
  - title: github
    url: http://github.com/archmix

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
