# Site settings
title: Archmix.org
email:
description: 

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://archmix.org" # the base hostname & protocol for your site

google_analytics: 
addthis_id: 
disqus_account: 

puzzly-devx-repo: https://github.com/archmix/puzzly-devx
puzzly-oss-repo: https://github.com/archmix/puzzly-oss

social:
  - title: twitter
    url: https://twitter.com/archmixorg
  - title: github
    url: http://github.com/archmix
  - title: slack
    url : https://join.slack.com/t/archmix/shared_invite/enQtODgxNTQ0Mjc4ODcwLWNiN2EwNDdmOTQzOTcyY2U2MjhmZWIzZDk5NGIwNDc2YTViNDY0NDc1ODVlNTg0NDU4YjFhZGE5ODY1NDNlOTM

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

collections:
  blueprint:
    output: true
  puzzly:
    output: true
